name: deploy-practice-kotlin

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: connect ec2 via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/practice-kotlin
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &

#      - name: hello world
#        run: echo "hello world!"
#
#      - name: multiple steps(|)
#        run: |
#          echo "good"
#          echo "bye"
#
#      - name: variable
#        run: |
#          echo $GITHUB_SHA
#          echo $GITHUB_REPOSITORY
